### ISSUE TITLE
Duplicate tx needs some persistence

### ISSUE THREAD

**Issue by cmeisl** [blocknative/assist#67]
from @mcutler...
UI tweak to how Transaction Awareness works:
1. The ‘This might be a duplicate transaction’ notification is among the most interesting/useful/powerful that we have.
2. But currently it automatically disappears as soon as a new alert shows up.
3. Now that we send a notification when MM transaction is requested, the ‘duplicate transaction’ notification is immediately dismissed and hence can’t be shown/
4. Can we make that message persist until manually dismissed? Or perhaps better until the associated transaction is resolved (confirmed or rejected)?

**Comment by aaronbarnardsound** [comment]
I think the best way to achieve this would to be change how we identify and manage transactions. 

Currently we are using the transaction hash as the unique identifier for each transaction which works great once a transaction has been confirmed/approved by the user and we have access to the transaction hash. Before the transaction has been confirmed/approved we don't have any way of removing/adding notifications that relate to a particular transaction without having a unique identifier.

To give us more fine grained control over the transaction toaster notifications we could:

- Upon a `txRequest` event, create a unique id that will be attached to that transaction for the entire duration of it's lifecycle
- Send that to the server as a `id` property on the transaction object
- The server would then need to include the `id` property in all transaction related communications so that the client can update the state for that particular transaction

This will add a lot more flexibility to how we handle the extra transaction information that `assist.js` provides like repeat transaction and awaiting approval etc.

**Comment by cmeisl** [comment]
@aaronbarnardsound I like the plan. If you send `id` in the `event.transaction` object, I will handle that on the backend so `txPool`, `txConfirm`, and `txFailed` will include the id.
